version: '3.7'
services:
  csgo:
    image: crazymax/csgo-server-launcher:latest
    container_name: csgo
    ports:
      - ${PORT}:${PORT}/udp
      - ${PORT}:${PORT}/tcp
      - 27005:27005/udp
    env_file:
      - '.env'
    volumes:
      - './config:/var/steamcmd/games/csgo/csgo/cfg'
      - '${CSGO_PATH}:/var/steamcmd/games/csgo'
      - '${STEAM_PATH}:/home/steam/Steam'
    tty: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    restart: always
    deploy:
      resources:
        limits:
          cpus: '${MAX_CPUS}'
          memory: ${MAX_RAM}
