version: '3.2'

services:
  updater:
    image: crazymax/csgo-server-launcher:latest
    container_name: csgo-updater
    command:
      - 'csgo-server-launcher'
      - 'update'
    env_file:
      - '.env'
    volumes:
      - './config:/var/steamcmd/games/csgo/csgo/cfg'
      - '${CSGO_PATH}:/var/steamcmd/games/csgo'
      - '${STEAM_PATH}:/home/steam/Steam'
    tty: true
    restart: on-failure
